export { AbsoluteNote } from './note/absolute-note';
export { IncompleteChord } from './chord/incomplete-chord';
export { Scale } from './scale';
export { Harmonizer, HarmonizerParameters } from './harmony/harmonizer';
export { RomanNumeral } from './harmony/roman-numeral';
export { Interval } from './interval/interval';
export { Note } from './note/note';
export { Accidental } from './accidental';
export { Progression, ProgressionPredicate, ProgressionProducer } from './harmony/progression';
export { ChordQuality } from './chord/chord-quality';
export { IntervalQuality } from './interval/interval-quality';
export { Key } from './key';
export { PartWritingParameters, PartWriting, defaultPartWritingParameters } from './part-writing/part-writing';
export { Expansion, ExpansionOperator } from './harmony/expansion';
export { Chord } from './chord/chord';
export { HarmonizedChord } from './chord/harmonized-chord';
export { CompleteChord } from './chord/complete-chord';
export { Motion } from './interval/motion';
export { ScaleDegree } from './harmony/scale-degree';
export { ComplexInterval } from './interval/complex-interval';
export { IChord } from './chord/ichord';
export { flattenResults, NestedIterable, resultsOfTotalLength, resultsOfLength, flattenResult } from './util/nested-iterable';
export { PartWriter, PartWriterParameters } from './part-writing/part-writer';