# This adapted from https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions
name: ci
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check Circular Dependencies
        run: pnpm dlx madge --circular --extensions ts ./src

      - name: Lint
        run: pnpm run lint --no-fix

  build:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/

      - name: Install Dependencies
        run: pnpm i

      - name: Unit Tests
        run: pnpm run test --verbose

  package-tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        progression:
          - I IV viio iii vi ii V I IV6 viio iii6 vi ii6 V
          - I6 viio6 I vi IV6 V43/V V viio7/V V vi IV6 V43/V V
        script:
          - success
          - failure
        ordering:
          - depth
          - default
        key:
          - Db
          - B

    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/

      - name: Install Dependencies For Test Script
        run: pnpm install
        working-directory: ./test/

      - name: Build Test Script
        run: pnpm run tsc
        working-directory: ./test/

      - name: Run Test
        run: node dist/${{ matrix.script }}.test.js -o ${{ matrix.ordering }} -k ${{ matrix.key }} ${{ matrix.progression }}
        working-directory: ./test/
        timeout-minutes: 10
