# This adapted from https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions
name: ci
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Check Circular Dependencies
        run: npx madge --circular --extensions ts ./src

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: Install Dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test -- --verbose

  package-tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [12.x]
        progression:
          - I iii IV7 V
          - I iii vi ii V
          - I ii65 V V42 I6 V43 I ii42 V65
          - I ii42 V65 I IV viio iii vi ii I64 V
        script:
          - success
          - failure
        ordering:
          - greedy
          - depth
          - default
        key:
          - C
          - Gb
          - F#
        check:
          - true
          - false

    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: Install Dependencies For Test Script
        run: npm ci
        working-directory: ./test/

      - name: Build Test Script
        run: tsc
        working-directory: ./test/

      - name: Run Test
        run: node dist/${{ matrix.script }}.test.js -k ${{ matrix.key }} -c ${{ matrix.check }} ${{ matrix.progression }}
        working-directory: ./test/
        timeout-minutes: 20