name: docs
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        
      - name: Get Version
        run: echo "::set-env name=version::$(node -p -e "require('./package.json').version")"

      - name: Get Changelog
        run: echo "::set-env name=changelog::$(git log --format=%B -n 1)"

      - name: NPM Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.publish.version }}
          release_name: Release v${{ steps.publish.version }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false